spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.232.209.98:3306/user-center
    username: user-center
    password: 123456
    # session失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0